const ALERT = 'ALERT'
const REFETCH_CHATS = 'REFETCH_CHATS';
const NEW_ATTACHMENT = 'NEW_ATTACHMENT';
const NEW_MESSAGE_ALERT = 'NEW_MESSAGE_ALERT';

const NEW_REQUEST = 'NEW_REQUEST';

const NEW_MESSAGE = 'NEW_MESSAGE';
export { ALERT, NEW_ATTACHMENT, NEW_MESSAGE, NEW_MESSAGE_ALERT, NEW_REQUEST, REFETCH_CHATS };

